
#spring:
#  datasource:
##   数据源基本配置
#    username: root
#    password: 123456
#    url: jdbc:mysql://localhost/spring_cache?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
#    driver-class-name: com.mysql.cj.jdbc.Driver
#
#
#
#
#
##  #如果用注解方式在这开启驼峰命名
#mybatis:
#  configuration:
#    map-underscore-to-camel-case: true
    





