server:
  port: 8200
spring:
  application:
    name: consume-user
eureka:
  instance:             
    prefer-ip-address: true  #注册服务的时候使用服务的ip地址
  client:
    service-url:
     defaultZone: http://localhost:8761/eureka/ #配置注册中心地址，如果不配置会用默认的，
                      
